openapi: 3.0.3
components:
  schemas:
    Course: 
      type: object
      properties:
        Id:
         type: string
        Name: 
          type: string
        Url:  
          type: string
        Description: 
          type: string
  